version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/hello-devops
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
      - run: npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test
          requires:
            - build
          filters:
            branches:
              only: develop
